upgrade ember-cli to 2.12.3
ciena-blueplanet/ember-validator-shim pull request #50
Opened 2017-06-30 15:40 UTC by helloWorldCindy

**This project uses [semver](http://semver.org), please check the scope of this pr:**

- [ ] #none# - documentation fixes and/or test additions
- [ ] #patch# - backwards-compatible bug fix
- [x] #minor# - adding functionality in a backwards-compatible manner
- [ ] #major# - incompatible API change

# CHANGELOG

Upgrade Ember-cli to 2.12.3

2017-06-30 16:03 UTC, juwara0 commented on .eslintrc.js
> +};
The semi-colon needs to be removed.

2017-06-30 16:03 UTC, juwara0 commented on ember-cli-build.js
>  var EmberAddon = require('ember-cli/lib/broccoli/ember-addon')
This should be updated to: `const EmberAddon = require('ember-cli/lib/broccoli/ember-addon')`

2017-06-30 16:03 UTC, juwara0 commented on package.json
>      "ember-cli-app-version": "^2.0.1",
This should be removed.

2017-06-30 16:03 UTC, juwara0 commented on package.json
>      "ember-cli-test-loader": "^1.1.1",
This should be removed.

2017-06-30 16:03 UTC, juwara0 commented on package.json
>      "ember-resolver": "^2.1.1",
This should be `"ember-resolver": "^2.0.3",`

2017-06-30 16:03 UTC, juwara0 commented on tests/.eslintrc.js
> +};
The semi-colon needs to be removed.

2017-06-30 17:52 UTC, helloWorldCindy commented on tests/.eslintrc.js
> +};
Fixed.

2017-06-30 17:52 UTC, helloWorldCindy commented on package.json
>      "ember-resolver": "^2.1.1",
Fixed.

2017-06-30 17:52 UTC, helloWorldCindy commented on package.json
>      "ember-cli-test-loader": "^1.1.1",
Fixed.

2017-06-30 17:52 UTC, helloWorldCindy commented on package.json
>      "ember-cli-app-version": "^2.0.1",
Fixed.

2017-06-30 17:52 UTC, helloWorldCindy commented on ember-cli-build.js
>  var EmberAddon = require('ember-cli/lib/broccoli/ember-addon')
Fixed.

2017-06-30 17:53 UTC, helloWorldCindy commented on .eslintrc.js
> +};
Fixed.

2017-07-03 13:40 UTC, notmessenger requested changes

2017-07-03 13:40 UTC, notmessenger commented on .npmignore
>  .jshintrc
Remove

2017-07-03 13:40 UTC, notmessenger commented on .npmignore
> +.eslintrc.js
Place this entry in the file alphabetically and remove the entry for `.eslintrc`

2017-07-03 13:40 UTC, notmessenger commented on .travis.yml
> +  - node_js: 'stable'
Do we want this @juwara0?  I have not been adding this to my PRs

2017-07-03 13:40 UTC, notmessenger commented on tests/dummy/config/environment.js
> +/* eslint-env node */
Also remove `ENV.rootURL = '/'` entry from test configuration

2017-07-07 12:26 UTC, juwara0 commented on .npmignore
>  .jshintrc
Fixed.

2017-07-07 12:26 UTC, juwara0 commented on .npmignore
> +.eslintrc.js
Fixed

2017-07-07 12:26 UTC, juwara0 commented on .travis.yml
> +  - node_js: 'stable'
Yes, lets keep this in for now.

2017-07-07 12:26 UTC, juwara0 commented on tests/dummy/config/environment.js
> +/* eslint-env node */
Fixed

2017-07-07 12:37 UTC, notmessenger commented on .travis.yml
> +  - npm install -g coveralls pr-bumper@^1.0.0
Do we want `1.0.0` or `2.0.0`?

2017-07-07 12:39 UTC, notmessenger approved these changes

2017-07-07 12:40 UTC, juwara0 commented on .travis.yml
> +  - npm install -g coveralls pr-bumper@^1.0.0
All the rest of the repos are running `1.0.0` this one was not. I would like to make the switch to `2.0.0` a separate effort.

2017-07-07 12:42 UTC, juwara0 commented
Approved.

2017-07-07 12:43 UTC, merged